#!/bin/bash
content="$(curl -L "https://raw.githubusercontent.com/coderofsalvation/flowee/master/README.md" | ./bashdown --html )"
printf "$(node_modules/.bin/brown template.html package.json)" "$content" "$(date)" > index.html
