// Generated by CoffeeScript 1.9.3
(function() {
  var fetch;

  fetch = require('node-fetch');

  module.exports = function(method, resource, data, cb) {
    var options;
    if (process.env.DEBUG) {
      console.log(method + " " + resource + " " + JSON.stringify(data, null, 2));
    }
    options = {
      method: method,
      headers: {
        "Content-Type": "application/vnd.api+json",
        "Accept": "application/vnd.api+json",
        "x-custom-token": process.env.APITOKEN || "123345"
      }
    };
    if (data) {
      options.body = JSON.stringify(data);
    }
    return fetch('http://localhost:1337' + resource, options).then(function(res, err) {
      if (res.headers.get('x-response-time')) {
        console.log("responsetime: " + res.headers.get('x-response-time'));
      }
      if (err) {
        console.dir(err);
      }
      return res.json();
    }).then(function(json, err) {
      if (process.env.DEBUG) {
        console.log(JSON.stringify(json, null, 2));
      }
      return cb(json);
    });
  };

}).call(this);
