#!/bin/bash
find -name "*.coffee" | grep -v node_modules | while read file; do
  echo "compiling ${file/coffee$/js/g}";
  #coffee -o lib -c "$file" ; git add "${file/coffee$/js/}";
  coffee -c "$file" ; git add "${file/coffee$/js/}";
done
echo "$(cat test/model.js | tail -n+3| head -n-2)" > test/model.js
git add test/model.js

